{
 "title": "Flask - Observabilidade Simples",
 "tags": [
  "flask",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de requisições",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(flask_http_request_total)", "legendFormat": "requests" }
   ]
  },
  {
   "title": "Requisições por rota",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    {
     "expr": "sum by (path) (rate(flask_http_request_total[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Tempo médio por rota",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(flask_http_request_duration_seconds_sum[1m])) / sum by (path) (rate(flask_http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requisições por status HTTP",
   "type": "bargauge",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (status) (flask_http_request_total)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Logs da API Flask",
   "type": "logs",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{container=\"flask-api\"}"
    }
   ]
  }
 ]
}